from typing import Any
from google import genai
from google.genai import types
from loguru import logger
from config.settings import get_settings

class LLMService:
    """
    LLM Client Service wrapper using the official google-genai SDK.
    Interfaces with Gemini models for text generation and analysis.
    """

    def __init__(self) -> None:
        self.settings = get_settings()
        self.client = None
        self.default_model = "gemini-2.5-pro"
        self._initialize_client()

    def _initialize_client(self) -> None:
        """
        Initializes the GenAI Client using the configured API key from settings or session state.
        """
        api_key = None
        try:
            import streamlit as st
            api_key = st.session_state.get("gemini_api_key")
        except Exception:
            pass
            
        if not api_key:
            api_key = self.settings.gemini_api_key
            
        if not api_key:
            logger.warning(
                "GEMINI_API_KEY is not set. LLMService will operate in dummy/mock mode."
            )
            return

        try:
            logger.info("Initializing official google-genai Client...")
            self.client = genai.Client(api_key=api_key)
            logger.info("GenAI Client successfully initialized.")
            try:
                logger.info("Querying available models for this API key...")
                for m in self.client.models.list():
                    logger.info(f"  - Supported Model Name: {m.name}")
            except Exception as list_err:
                logger.warning(f"Could not list models: {list_err}")
        except Exception as e:
            logger.error(f"Failed to initialize GenAI client: {e}")
            self.client = None

    def generate_text(self, prompt: str, system_instruction: str | None = None, enable_search: bool = False) -> str:
        """
        Generates text using the Gemini model, optionally enabling Google Search grounding,
        with built-in exponential backoff retries for 429 Resource Exhausted rate limits.
        """
        import time
        if not self.client:
            self._initialize_client()
            
        if not self.client:
            logger.warning("LLMService: Client not initialized. Returning placeholder response.")
            return (
                f"[MOCK RESPONSE] CareerForge Engine: Processed prompt of length {len(prompt)} "
                "successfully. Set your GEMINI_API_KEY to receive actual AI-generated content."
            )

        max_retries = 5
        for attempt in range(1, max_retries + 1):
            try:
                logger.info(f"Generating content for prompt (length: {len(prompt)})...")
                
                tools = [types.Tool(google_search=types.GoogleSearch())] if enable_search else None
                config = types.GenerateContentConfig(
                    tools=tools
                )
                if system_instruction:
                    config.system_instruction = system_instruction

                # Call the official SDK
                response = self.client.models.generate_content(
                    model=self.default_model,
                    contents=prompt,
                    config=config
                )
                
                if response and response.text:
                    return response.text
                
                logger.warning("LLM returned an empty response.")
                return "No content generated by the model."

            except Exception as e:
                err_msg = str(e)
                if "429" in err_msg or "RESOURCE_EXHAUSTED" in err_msg or "quota" in err_msg.lower():
                    sleep_time = min(2 ** attempt + attempt, 15)
                    logger.warning(
                        f"429 Resource Exhausted / Rate limit hit during generate_text. "
                        f"Retrying in {sleep_time}s... (Attempt {attempt}/{max_retries})"
                    )
                    time.sleep(sleep_time)
                else:
                    logger.error(f"Error during content generation: {e}")
                    return f"Error: Failed to generate content from AI model ({e})."
        
        logger.error("Failed to generate content after maximum retries due to rate limits.")
        return "Error: Rate limit exceeded. Please try again in a moment."

    def generate_structured_data(self, prompt: str, schema: type, system_instruction: str | None = None, enable_search: bool = False) -> Any:
        """
        Generates structured JSON data conforming to a Pydantic schema using Gemini,
        with built-in exponential backoff retries for 429 Resource Exhausted rate limits.
        """
        import time
        if not self.client:
            self._initialize_client()
            
        if not self.client:
            logger.warning("LLMService: Client not initialized. Returning None for structured data.")
            return None

        max_retries = 5
        for attempt in range(1, max_retries + 1):
            try:
                logger.info(f"Structured data generation requested for schema: {schema.__name__}")
                
                tools = [types.Tool(google_search=types.GoogleSearch())] if enable_search else None
                config = types.GenerateContentConfig(
                    response_mime_type="application/json",
                    response_schema=schema,
                    tools=tools
                )
                if system_instruction:
                    config.system_instruction = system_instruction

                response = self.client.models.generate_content(
                    model=self.default_model,
                    contents=prompt,
                    config=config
                )

                if response and response.parsed:
                    return response.parsed

                logger.warning("LLM returned no parsed structured data.")
                return None
            except Exception as e:
                err_msg = str(e)
                if "429" in err_msg or "RESOURCE_EXHAUSTED" in err_msg or "quota" in err_msg.lower():
                    sleep_time = min(2 ** attempt + attempt, 15)
                    logger.warning(
                        f"429 Resource Exhausted / Rate limit hit during generate_structured_data. "
                        f"Retrying in {sleep_time}s... (Attempt {attempt}/{max_retries})"
                    )
                    time.sleep(sleep_time)
                else:
                    logger.error(f"Error during structured data generation: {e}")
                    return None
        
        logger.error("Failed to generate structured data after maximum retries due to rate limits.")
        return None
