from typing import Any
from google import genai
from google.genai import types
from loguru import logger
from config.settings import get_settings

class LLMService:
    """
    LLM Client Service wrapper using the official google-genai SDK.
    Interfaces with Gemini models for text generation and analysis.
    """

    def __init__(self) -> None:
        self.settings = get_settings()
        self.client = None
        self.default_model = "gemini-2.5-flash"
        self._initialize_client()

    def _initialize_client(self) -> None:
        """
        Initializes the GenAI Client using the configured API key.
        """
        api_key = self.settings.gemini_api_key
        if not api_key:
            logger.warning(
                "GEMINI_API_KEY is not set in environment or settings. "
                "LLMService will operate in dummy/mock mode."
            )
            return

        try:
            logger.info("Initializing official google-genai Client...")
            # Official google-genai client initialization
            self.client = genai.Client(api_key=api_key)
            logger.info("GenAI Client successfully initialized.")
        except Exception as e:
            logger.error(f"Failed to initialize GenAI Client: {e}")
            self.client = None

    def generate_text(self, prompt: str, system_instruction: str | None = None) -> str:
        """
        Generates text using the Gemini model.
        Returns a mock/fallback string if the client is not initialized.
        """
        if not self.client:
            logger.warning("LLMService: Client not initialized. Returning placeholder response.")
            return (
                f"[MOCK RESPONSE] CareerForge Engine: Processed prompt of length {len(prompt)} "
                "successfully. Set your GEMINI_API_KEY to receive actual AI-generated content."
            )

        try:
            logger.info(f"Generating content for prompt (length: {len(prompt)})...")
            
            config = types.GenerateContentConfig()
            if system_instruction:
                config.system_instruction = system_instruction

            # Call the official SDK
            response = self.client.models.generate_content(
                model=self.default_model,
                contents=prompt,
                config=config
            )
            
            if response and response.text:
                return response.text
            
            logger.warning("LLM returned an empty response.")
            return "No content generated by the model."

        except Exception as e:
            logger.error(f"Error during content generation: {e}")
            return f"Error: Failed to generate content from AI model ({e})."

    def generate_structured_data(self, prompt: str, schema: type, system_instruction: str | None = None) -> Any:
        """
        Generates structured JSON data conforming to a Pydantic schema using Gemini.
        
        TODO: Implement JSON schema parsing and structured generation using
              types.GenerateContentConfig(response_mime_type="application/json", response_schema=schema)
        """
        logger.info(f"Structured data generation requested for schema: {schema.__name__}")
        # Placeholder for structured JSON generation
        pass
